apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  argocd-image-updater.argoproj.io/image-list: rumrum/minesweeper:~0.0
  name: minesweeper-app
spec:
  project: default
  source:
    repoURL: 'git@github.com:rumnow/minesweeper.git'
    targetRevision: main
    path: infra
  destination:
    name: ''
    namespace: minesweeper
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
