apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo
  namespace: minesweeper
spec:
  project: default
  source:
    repoURL: git@github.com:rumnow/minesweeper.git
    targetRevision: main
    path: infra/helm/mongodb
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
