apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo
spec:
  destination:
    name: ''
    namespace: minesweeper
    server: 'https://kubernetes.default.svc'
  source:
    path: infra/helm/mongodb
    repoURL: 'git@github.com:rumnow/minesweeper.git'
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
