name: ci

on:
  push:
    branches:
      - "main"

env:
  TEST_TAG: rumrum/minesweeper:test
  LATEST_TAG: rumrum/minesweeper:latest
  PATH_TAG: rumrum/minesweeper

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: back
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          docker run -d -p 8080:8080 ${{ env.TEST_TAG }}
          sleep 5
          nc -zv 127.0.0.1 8080

      - name: Stop and Clean Up
        run: |
          docker stop $(docker ps -q)
          docker rm $(docker ps -aq)

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: back
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}

      - name: Get Docker image digest
        id: get_image_digest
        run: |
          IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.LATEST_TAG }})
          echo "IMAGE_DIGEST=$IMAGE_DIGEST" >> $GITHUB_ENV

      - name: Push Docker image with digest tag
        run: |
          docker push "${{ env.PATH_TAG }}:${{ env.IMAGE_DIGEST }}"

      - name: Deploy new Docker image on the target server
        run: |
          ssh-keyscan -H ${{ secrets.SSH_SERVER_IP }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER_IP }} <<EOF
            docker pull user/app:${{ env.IMAGE_DIGEST }}
            docker stop your_container_name || true
            docker run -d -p 8080:8080 --name your_container_name user/app:${{ env.IMAGE_DIGEST }}
          EOF
