name: ci

on:
  push:
    branches:
      - "main"

env:
  TEST_TAG: rumrum/minesweeper:test
  LATEST_TAG: rumrum/minesweeper:latest
  PATH_TAG: rumrum/minesweeper
  COMMIT_HASH: ${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: back
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          docker run -d -p 8080:8080 ${{ env.TEST_TAG }}
          sleep 5
          nc -zv 127.0.0.1 8080

      - name: Stop and Clean Up
        run: |
          docker stop $(docker ps -q)
          docker rm $(docker ps -aq)

      - name: Build Docker image
        run: |
          cd back
          docker build -t ${{ env.PATH_TAG }}:${{ env.COMMIT_HASH }} .
          docker push ${{ env.PATH_TAG }}:${{ env.COMMIT_HASH }}
        env:
          DOCKER_BUILDKIT: 1

      - name: Deploy new Docker image on the target server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_SERVER_IP }} -p18022 <<EOF
            sudo docker pull ${{ env.PATH_TAG }}:${{ env.COMMIT_HASH }}
            sudo docker stop minesweeper && sudo docker rm minesweeper || true
            sudo docker run -d -p 8080:8080 --network jj_network --name minesweeper ${{ env.PATH_TAG }}:${{ env.COMMIT_HASH }}
          EOF

